---
title: "R Notebook"
output: html_notebook
---

packages
```{r}
library(tidyverse)
library(plotly)
library(leaflet) 
library(magrittr)
library(stringr)
library(rpivotTable)
```

Read in data
```{r}
download.file("https://opendata.socrata.com/api/views/ddym-zvjk/rows.csv?accessType=DOWNLOAD",destfile="data.csv",method="libcurl")

# Base R
# starbucks1 <- read.csv("data.csv")

# readr
starbucks <- read_csv("data.csv")

# is this needed? as_tibble(starbucks)

# rename(starbucks, `StoreNumber` =  `Store Number` )

#Make State a factor for later on
#starbucks$State.f <- factor(starbucks$State)
#is.factor(starbucks$State.f)

class(starbucks)

#View(starbucks2)

starbucks


```

Let's now subset it for PA
```{r}

# Base R
# starbucks <- starbucks1[ which(starbucks1$State=='VA' & starbucks1$Country== 'US'), ]

# Dplyr
# Without pipes
# starbucks_MO <- filter(starbucks, Country== 'US', State=='VA')

starbucks_PA <- starbucks %>%
  filter(Country== 'US', State=='PA')%>% 
  select(Brand, `Store Number`, `Ownership Type`, City,	State,	Zip, Country, Coordinates,	Latitude,	Longitude, Name)

```

```{r}

leaflet() %>% addTiles() %>% setView(-89.360922, 43.226851, zoom = 12) %>% 

addMarkers(data = starbucks_PA, lat = ~ Latitude, lng = ~ Longitude, popup = starbucks_PA$Name) %>%
  addPopups(-80.003440, 40.441910, 'the <b> spot</b>')

```


```{r}
# Base R
# starbucks1 <- read.csv("data.csv")

# Dplyr
starbucks_R_C_P <- read_csv("data/starbucks_R_C_P.csv")

# rename(starbucks_R_C_P, StoreNumber = `Store Number`)

class(starbucks_R_C_P)

#View(starbucks2)

```
Excel
```{r}
starbucks_PA_R_C_P <- starbucks_PA %>%
  left_join(starbucks_R_C_P, by = 'Store Number')

#rename(starbucks_R_C_P, StoreNumber = `Store Number`)

#starbucks_MO_R_C_P$`Ownership Type.f` <- #factor(starbucks_MO_R_C_P$`Ownership Type`)
#is.factor(starbucks_MO_R_C_P$`Ownership Type.f`)

starbucks_PA_R_C_P

```



```{r}
ggplot(data = starbucks_PA_R_C_P) +
  geom_bar(mapping = aes(x = `Ownership Type`))
```


```{r}

ggplot(data = starbucks) +
  geom_bar(mapping = aes(x = `State`))
```

```{r}

options(scipen=10000)

ggplot(starbucks_PA_R_C_P, aes(P)) + 
  geom_histogram()

```

```{r}

options(scipen=10000)

ggplot(starbucks_PA_R_C_P, aes(x=C, y=`Ownership Type`)) + geom_point()

```


```{r}
plot(iris$Sepal.Width, 
 iris$Sepal.Length)
```

```{r}
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) + geom_point() + stat_smooth(method="lm")
```

```{r}
gg <- ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) + geom_point() + stat_smooth(method="lm") + theme(panel.background = element_rect(fill = "lightcyan"), 
    plot.background = element_rect(fill = "cornsilk2"))

gg + theme(axis.line = element_line(size = 1.5), 
    panel.grid.major = element_line(colour = "honeydew4"), 
    axis.title = element_text(size = 20), 
    plot.title = element_text(size = 20), 
    panel.background = element_rect(fill = "whitesmoke"), 
    legend.position = c(0.75, 0.75))
```

```{r}
summary(diamonds)

summary(diamonds$price)

aveSize <- round(mean(diamonds$carat), 4)
clarity <- levels(diamonds$clarity)

p <- qplot(carat, price, data = diamonds, color = clarity) + labs(x = "Carat", y = "Price") + labs(title = "Diamond Pricing")

p + theme(plot.title = element_text(size = 24))
```

```{r}


summary(diamonds)

summary(diamonds$price)

aveSize <- round(mean(diamonds$carat), 4)
clarity <- levels(diamonds$clarity)

p <- qplot(carat, price, data = diamonds, color = clarity) + labs(x = "Carat", y = "Price") + labs(title = "Diamond Pricing")

p + theme(plot.title = element_text(size = 24))

ggplotly(p)

```


```{r}

iris %>%
tbl_df %>%
filter( Sepal.Width > 3 ) %>%
rpivotTable

rpivotTable(mtcars, rows="gear", col="cyl", aggregatorName="Average", 
vals="mpg", rendererName="Treemap")


rpivotTable(mtcars,rows="gear", cols=c("cyl","carb"),width="100%", height="400px")

```

```{r}

rpivotTable(starbucks_IL_R_C_P, width="100%", height="400px")

```
